initial commit of the newest pdf scraper
FinHubSA/AK-PDF-Scraper pull request #1
Opened 2022-06-14 09:50 UTC by DanaeBouwer

**Major Adjustments and restructuring of pdf scraper**

_Summary_
The new scraper takes its input from the masterlist, and loops through a list of article ID's. It directly navigates to the article download page on JSTOR, and automatically downloads it from there. This scraper also integrates the reCAPTCHA solver which was restructured by incorporating cookies to make sure the user stays logged in for the mp3 download and audio recognition to text transformation.

2022-06-15 07:55 UTC, wenkanglu requested changes
General comments:
* We should use a dependency manager like [_Poetry_](https://python-poetry.org/) to keep track of dependencies of the project. It'll also allow whoever else working on this repository to easily download all dependencies.
* Make use of a formatter like [_Black_](https://github.com/psf/black) for consistent styling.
* Follow PEP8 for additional styling and naming conventions.
* Rename Masterlist_Scraper.py to main.py since it is the entry point to the application.
* Remove unnecessary committed files/folders like __pycache__.
* Remove Metadata.csv and Metadata.json and store them in something like Google Drive and point them out in a README. The files are too large and makes pushing and pulling cumbersome.

2022-06-15 07:55 UTC, wenkanglu commented on Masterlist_Scraper.py
> +    })
This can all be outside of the loop since none of it changes between iterations.

2022-06-15 07:55 UTC, wenkanglu commented on Masterlist_Scraper.py
> +    #         driver.add_cookie(cookie)
Remove if not needed.

2022-06-15 09:39 UTC, DanaeBouwer commented on Masterlist_Scraper.py
> +    })
Cool, done!

2022-06-15 09:40 UTC, DanaeBouwer commented on Masterlist_Scraper.py
> +    #         driver.add_cookie(cookie)
Made the change.

2022-06-21 08:58 UTC, wenkanglu requested changes
Rather minor changes that you can just add with your next commit.

2022-06-21 08:58 UTC, wenkanglu commented on src/connection_controllers/gen_connection_controller.py
>      def __init__(self, driver: webdriver, host: str):
I do not recommend placing any logic in the __init__ function. The __init__ function serves as the "constructor" to our class and should only be used to assign local variables to self. Any additional logic should be placed in their own function and then called upon externally.

2022-06-21 08:58 UTC, wenkanglu commented on src/main.py
> +        while t_c_accepted != True:
Can be simplified to `while !t_c_accepted:`

Also, this is potentially infinite if something goes wrong and the t&c's are never accepted. We should add a maximum number of tries (same as any other potentially infinite while loop).

You can do something like `while !t_c_accepted and current_try < MAX_TRIES_FOR_T&C`

In fact, once we do this, we can then log when this maximum number of tries has taken place and we can see where our bottlenecks are during analysis.

2022-06-21 08:58 UTC, wenkanglu commented on src/main.py
>          if restart == True:
`if restart`

2022-06-21 08:58 UTC, wenkanglu commented on src/main.py
> +        while file == url_pending:  # and count <= 60:
Why is the count commented out? We want to avoid infinite loops at all cost.

2022-06-21 08:58 UTC, wenkanglu commented on src/recaptcha_solver.py
>  def delay():
Rather add the minimum and maximum time to wait as parameters so you can reuse this delay function wherever you need a random amount of time to wait.

2022-06-21 08:58 UTC, wenkanglu commented on src/recaptcha_solver.py
>      while recaptcha_control == True:
`while recaptcha_control`
Although the variable name does not really sound like a boolean. Maybe think of a different name here.

2022-06-21 08:58 UTC, wenkanglu commented on src/recaptcha_solver.py
> +            while recaptcha_challenge == True:
`while recaptcha_challenge`

Change name to be more of a boolean.

2022-06-21 08:58 UTC, wenkanglu commented on src/recaptcha_solver.py
> +                    if check_solved(driver, url, url_pending) == True:
` if check_solved(driver, url, url_pending):`

2022-06-21 08:58 UTC, wenkanglu commented on src/temp_storage.py
> +    def getTempStoragePath():
Please be consistent with naming. In Python we prefer snake case, e.g., `get_temp_storage_path`

2022-06-22 08:42 UTC, DanaeBouwer commented on src/main.py
> +        while t_c_accepted != True:
The while !t_c_accepted is not working, but adjusted that section to avoid a possible infinite loop.

2022-06-22 08:43 UTC, DanaeBouwer commented on src/main.py
> +        while file == url_pending:  # and count <= 60:
It was for a test, have uncommented it.

2022-06-22 08:46 UTC, DanaeBouwer commented on src/recaptcha_solver.py
>  def delay():
I added a module that calculates the 5 point moving average download time of the user. I replaced the delay function with this and re-use it throughout the programme.

2022-06-22 08:50 UTC, DanaeBouwer commented on src/recaptcha_solver.py
>      while recaptcha_control == True:
There are two frames in the reCAPTCHA: a control frame and a challenge frame. I therefore called the respective while loops for each section, recaptcha_control and recaptcha_challenge. Do you still thing the naming convention should be changed?

2022-06-22 08:50 UTC, wenkanglu commented on src/main.py
> +        while t_c_accepted != True:
Try "while not t_c_accepted". Forgot that this was Python lol

2022-06-22 08:52 UTC, DanaeBouwer commented on src/recaptcha_solver.py
> +            while recaptcha_challenge == True:
Same as the recaptcha_control. Let me know if I should change it.

2022-06-22 08:56 UTC, DanaeBouwer commented on src/temp_storage.py
> +    def getTempStoragePath():
Got it, thanks!

2022-06-22 09:00 UTC, wenkanglu commented on src/recaptcha_solver.py
>      while recaptcha_control == True:
Yeah so a boolean should always be asking a question in the form of "Is something true or false". A recaptcha control or challenge being true is vague as to what that really means. For example, if it is regarding whether the control is active, then `is_recaptcha_control_active` is a better name.

2022-06-22 09:03 UTC, DanaeBouwer commented on src/recaptcha_solver.py
>      while recaptcha_control == True:
Okay, makes sense! Will change the naming appropriately.

2023-02-08 08:31 UTC, merged